# Generated by Django 5.1.3 on 2025-01-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadjob',
            name='location',
        ),
    ]
