# Generated by Django 5.1.3 on 2025-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadjob_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadjob',
            name='jobstatus',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
