# Generated by Django 5.1.4 on 2025-01-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_uploadjob_jobstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobappliedat', models.DateTimeField(auto_now_add=True)),
                ('jobstatus', models.CharField(default='Applied', max_length=100)),
                ('resume', models.FileField(upload_to='static/assets\\Resume')),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadjob')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
            options={
                'db_table': 'ApplyJob',
            },
        ),
    ]
