# Generated by Django 5.1.4 on 2025-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
