# Generated by Django 5.1.4 on 2025-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_applyjob_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='textquestion',
            field=models.TextField(null=True),
        ),
    ]
